export const  ChatTypes = {
    GET_USERS_REQUEST: '@chat/GET_USERS_REQUEST',
    GET_USERS_SUCCESS: '@chat/GET_USERS_SUCCESS',

    SET_USER_DESTINY: '@chat/SET_USER_DESTINY',
    
    GET_CHAT_REQUEST:'@chat/GET_CHAT_REQUEST',
    GET_CHAT_SUCCESS:'@chat/GET_CHAT_SUCCESS',

    POST_MESSAGE_REQUEST: '@chat/POST_MESSAGE_REQUEST',
    POST_MESSAGE_SUCCESS: '@chat/POST_MESSAGE_SUCCESS',

    MARK_AS_READ_REQUEST: '@chat/MARK_AS_READ_REQUEST',
    MARK_AS_READ_SUCCESS: '@chat/MARK_AS_READ_SUCCESS',
}