export const AuthTypes = {
  REGISTER_USER_REQUEST: "@auth/REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS: "@auth/REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "@auth/REGISTER_USER_FAILURE",

  LOGIN_USER_REQUEST: "@auth/LOGIN_USER_REQUEST",
  LOGIN_USER_SUCCESS: "@auth/LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "@auth/LOGIN_USER_FAILURE",

  SET_USER_LOGGED: "@auth/SET_USER_LOGGED",
  LOGOUT_USER: "@auth/LOGOUT_USER",

  CLEAR_STATE: "@auth/CLEAR_STATE"
};
